services:
  anvil:
    container_name: anvil
    image: ghcr.io/foundry-rs/foundry:latest
    ports:
      - ${ANVIL_RPC_PORT:-8545}:8545
    command:
      - anvil -m "${MNEMONIC}" --host "0.0.0.0" --fork-url ${RPC_FORK_URL} --fork-block-number ${RPC_FORK_BLOCK}
    networks:
      - proxy-network

  otterscan:
    container_name: otterscan
    image: otterscan/otterscan:latest
    restart: "always"
    ports:
      - ${OTTERSCAN_PORT:-8000}:80
    environment:
      ERIGON_URL: http://127.0.0.1:8545/

networks:
  proxy-network:
    name: custom_network
